cs-pub-ro/operating-systems

content/misc/lab-setup.md
Current link in lab-setup.md points to `https://github.com/open-education-hub/operating-systems`. This PR changes the link to `https://github.com/cs-pub-ro/operating-systems`.
=> Update link to GitHub repo in lab-setup.md

config.yaml, content/misc/rules-and-grading.md
Add initial version of the rules for the Operating Systems course inspired by the previous version on OCW.
This version contains TODOs and TBAs.
=> misc: Add grading rules from ocw

content/chapters/software-stack/lab/content/syscall-wrapper.md
Word should be past participle, not syscall name.
=> software-stack/lab: Remove backticks

content/assignments/mini-libc/README.md
Update `README.md` with current structure of directory (e.g. use `src/` instead of `libc/`). Detail use of `grade.sh` and `make lint`.
=> `asg/mini-libc`: Update `README.md`

content/assignments/async-web-server/tests/grade.sh, content/assignments/memory-allocator/tests/grade.sh, content/assignments/mini-libc/tests/grade.sh, content/assignments/minishell/checker/grade.sh, content/assignments/parallel-graph/tests/grade.sh, content/common/projects/grade.sh
The `grade.sh` script computes the final project grade, from two components: checker output and style checking.
Currently, checker output provides a maximum of 90 points and style checking an output of maximum 10 points, for a total maximum of 100 points.
Script it to be symlinked to the `tests/` directory of each project. It invokes the `check` rule and the `lint` rule in the tests Makefile, then proceeds to compute the summary result.
=> `common`: Add script to compute final project grade

content/chapters/software-stack/lab/support/common-functions/Makefile
Missing `-fno-builtin` flag from `Makefile` caused the compiler to substitute `str*` calls from `content/chapters/software-stack/lab/support/common-functions/main_string` with builin functions, instead of use custom implementations from `content/chapters/software-stack/lab/support/common-functions/string.c`.
=> lab/software-stack: Add missing -fno-builtin flag in Makefile

content/chapters/data/lab/content/investigate-memory.md
When using `mtrace`, the program needs to be loaded with the malloc debugging library. Use `LD_PRELOAD` for that. This may not be required for certain systems. Also, the file path used for `LD_PRELOAD` may be required to be updated, depending on the Linux distribution used.
=> `data/lab`: Use `LD_PRELOAD` for `mtrace`

.github/workflows/pr-deployment.yml
The URL was `http://open-education-hub.github.io/...`. This was incorrect for forked repos as it referred to the original owner: OEH. In addition, it was using the `http` scheme instead of `https`. This was less of an issue because the `http` endpoint redirects to `https`.
This commit fixes both of the aforementioned problems by dynamically obtaining the owner uwing `${{ github.repository_owner }}` and by using `https` instead of `http`.
=> actions/pr-deployment: Fix deployment URL

content/assignments/memory-allocator/README.md, content/assignments/memory-allocator/tests/Makefile, content/assignments/memory-allocator/tests/run_tests.py
Update `README.md` with testing updates. Apply fixes in `tests/Makefile`.
=> `asg/mem-alloc`: Update README and fix test script name

content/assignments/memory-allocator/.vscode/launch.json, content/assignments/memory-allocator/README.md, content/assignments/memory-allocator/tests/Makefile, content/assignments/memory-allocator/tests/ref/test-malloc-split-one-block.ref, content/assignments/memory-allocator/tests/ref/test-realloc-split-one-block.ref, content/assignments/memory-allocator/tests/snippets/test-malloc-split-one-block.c, content/assignments/memory-allocator/tests/snippets/test-realloc-split-one-block.c
* Sync with GitLab:
* Add vscode script for running and debugging the assignment's tests.
* Use python3 instead of Python in Makefile and README.md.
* Remove block expansion from `split-one-block` test
=> asg/mem-alloc: Remove block expansion from split-one-block test

config.yaml, content/misc/resources.md
Add resources for the Operating Systems course.
=> misc: Add resources from OCW

content/chapters/compute/lab/support/sum-array-bugs/seg-fault/Makefile
Add `-pthread` to LDFLAGS when compiling using `<pthread.h>`.
=> compute/fix sum-array-bugs/seg-fault Makefile

content/assignments/parallel-graph/README.md, content/assignments/parallel-graph/src/Makefile, content/assignments/parallel-graph/src/os_graph.c, content/assignments/parallel-graph/src/os_graph.h, content/assignments/parallel-graph/src/os_list.h, content/assignments/parallel-graph/src/os_threadpool.c, content/assignments/parallel-graph/src/os_threadpool.h, content/assignments/parallel-graph/src/parallel.c, content/assignments/parallel-graph/src/serial.c, content/assignments/parallel-graph/tests/Makefile, content/assignments/parallel-graph/utils/log, content/assignments/parallel-graph/utils/utils.h
Make overhaul update of the assignment: skeleton implementation, README, Makefiles.
=> asg/parallel-graph: Update assignment

.github/pull_request_template.md, CONTRIBUTING.md
This improves the guides on how to create commits with information about signatures, titles, descriptions and setting the user name and email appropriately. In addition, this adds a PR template with checks regarding the commit guidelines and testing.
=> contributing: Add detailed description on how to make commits

content/chapters/compute/lab/content/synchronization.md
Fix incorrect function name: replaced pthread_mute_unlock() with pthread_mutex_unlock().
=> compute/lab: Fix incorrect function name

content/chapters/compute/lab/content/arena.md, content/chapters/compute/lab/content/synchronization.md
Calling `strace -e clone ./sum_array_threads 2` would not show the clone3 syscall.
Replacing `clone` with `clone,clone3` in both commands allows the syscalls to display as expected.
A small typo has also been fixed.
=> Update command to show expected output

content/chapters/io/lab/content/redirections.md
The current table header is missing some spaces that are present in the `lsof` command output, making it slightly harder to follow due to the column misalignment. This pull request adds the spaces back.
=> io/lab: Fix lsof table header alignment in Redirections

content/chapters/io/lab/solution/mini-shell/mini_shell.c, content/chapters/io/lab/support/mini-shell/mini_shell.c
Currently the code fails to compile because `strtok_r` is not provided the `saveptr` argument.
This pull request fixes this and synchronizes the changes to the solution. It also removes the `TODO:` marker from one of the comments as there is nothing to do.
=> io/lab: Fix strtok_r usage in Mini-shell

content/chapters/app-interact/lecture/slides/defs.md
- [n/a] Tested your changes against relevant architectures and platforms;
- [n/a] Updated relevant documentation (if needed).
The slides were incorrectly referencing demos in the `demo/send-receive/` folder, which doesn't exits. This replaces `send-receive` with the correct folder name: `comm-channels`.
=> app-interact/lecture: Change reference to reader/sender demo

content/chapters/io/lab/quiz/mmap-read-write-benchmark.md, content/chapters/io/lab/quiz/syscalls-cp.md
`coreutils` 9.0 reimplemented `cp` using the `copy_file_range()` syscall, which performs zero-copy [1]. Therefore, the existing comparison between `mmap_cp` and `cp` is no longer valid. This commit mentions the new implementation and its effects on performance. This version of `coreutils` is available by default on newer Ubuntu systems such as 23.04.
[1] https://lists.gnu.org/archive/html/info-gnu/2021-09/msg00010.html
=> io/lab/quiz: Mention `copy_file_range` syscall for `cp`

chapters/general/drills/tasks/benchmarking-application.md, config.yaml
Add Markdown file storing the question scenario and the questions Modify config.yaml to render the new task
- Modify config.yaml to render the new task
=> general/drills: Add "Benchmarking Application" written task as exam

chapters/general/drills/tasks/aggregator-application.md, config.yaml
Add Markdown file storing the question scenario and the questions Modify config.yaml to render the new task
- Modify config.yaml to render the new task
=> general/drills: Add "Aggregator Application" written task as exam

chapters/general/drills/tasks/database-application.md, config.yaml
edited config.yaml and database-application.md
- Modify `config.yaml` to render the new task
=> general/drills: Add "Database Application" written task as exam

chapters/general/drills/tasks/faas-application.md, config.yaml
edited config.yaml and faas-service.md
=> general/drills: Add "FaaS service" written task as exam

chapters/software-stack/modern-software-stacks/slides/modern-software-stacks.md, chapters/software-stack/operating-system-types/slides/os-types.md, chapters/software-stack/operating-system/slides/operating-system.md, chapters/software-stack/overview/slides/software-stack.md, chapters/software-stack/software-types/slides/types-of-software.md
The links were made to `../media/<image-name>` in each subchapter's `slides/` folder. This made them work properly in the Markdown files in which they were imported, but not when those files were aggregated into the chapter-wide `slides.md` via MarkdownPP. The new links use paths starting from `slides.md`'s location and no longer work in their corresponding sub-files.
=> chapters/software-stack: Fix links to immages in the slids

content/misc/lab-setup.md
Since we will only be using VMs / native setups from now on, remove the Docker container references from the setup instructions.
=> misc/lab-setup: Remove Docker references

config.yaml
The name of the quiz file was incorrect in the config file.
=> config: Replace "Syscall Tool" quiz with "Libc"

chapters/software-stack/libc/drills/tasks/common-functions/solution/src/.gitignore, chapters/software-stack/libc/drills/tasks/common-functions/solution/src/os_string.c
The solution provided to `os_strcat()` was too esotheric and not suited to be used by students wanting go learn how to implement `strcat()`. The current solution is a bit more verbose, but still includes the previous approac as a nice-to-know gimmick.
=> chapters/software-stack: Simplify `os_strcat()` implementation.

chapters/data/memory-security/drills/tasks/exec-shellcode/support/tests/Makefile, chapters/data/process-memory/drills/tasks/page-mapper/support/tests/Makefile, chapters/data/working-with-memory/drills/tasks/access-counter/support/tests/Makefile, chapters/software-stack/libc/drills/tasks/common-functions/solution/tests/Makefile, chapters/software-stack/libc/projects/mini-libc/tests/Makefile
Fix paths for both `chapters/software-stack` and `chapters/data` so that users with white spaces in directory names can run the Makefile with no error
=> chapters/software-stack: Fix paths

config.yaml, gen-view.py
The lab_structure in config.yaml should only contain the 'content' list, comprising of the files that should be concatenated. gen-view.py takes these files and merges them together without changing their order.
To accomodate these changes, filenames in config.yaml must be prefixed with the content type (reading/, tasks/, guides/). For convenience 'reading/' prefix is optional.
**Facilitates: GH-#112**
=> infra/gen-view: Order sections based on config.yaml

chapters/data/memory-security/drills/tasks/bypassing-stack-protector/support/Makefile
Remove `-fno-stack-protector` option from Makefile in order to include the stack canary to be bypassed.
=> chapters/data/memory-security: Fix "Bypassing the Stack Protector" Task

chapters/data/memory-security/drills/tasks/pointer-arithmetic-leak/README.md
Replaced pointer-arithmetic-leak guide path
from `bypassing-stack-protector`
to `pointer-arithmetic-leak`.
=> chapters/data/memory-security: Fix drill path

chapters/compute/copy-on-write/slides/copy-on-write.md, chapters/compute/overview/slides/intro.md, chapters/compute/processes/slides/fork.md, chapters/compute/processes/slides/processes.md, chapters/compute/scheduling/slides/scheduling-algorithms.md, chapters/compute/scheduling/slides/scheduling.md, chapters/compute/synchronization/slides/mutual-exclusion.md, chapters/compute/synchronization/slides/synchronization.md, chapters/compute/synchronization/slides/thread-safety.md
Change links to `<subchapter-name/media/image-name>` to fit the new layout created by #95.
=> chapters/compute: Fix links to images

chapters/compute/Makefile, chapters/compute/scheduling/slides/scheduling-algorithms.md, chapters/compute/synchronization/slides/synchronization.md
Update Makefile to generate all gifs in the media directory. Reference the images using `<section>/media/<file>` to enable rendering on Docusaurus, even though it breaks in-file links.
=> compute/lectures: Fix paths to generated gifs

config.yaml
The task requires knowledge of `fork()` and `execve()`, the latter being taught in lab 7.
=> chapters/compute: Move `mini-shell` task from lab 6 to 7

chapters/io/file-descriptors/drills/tasks/mmap_cp/solution/src/mmap_cp.c, chapters/io/file-descriptors/drills/tasks/my-cat/solution/src/my_cat.c
As per the `read` and `write` syscall wrappers, the functions return the number of bytes that have been successfully read or written. The buffer offset should be updated accordingly, as implemented.
=> chapters/io: Fix wwrite and rread logic from my-cat

content/assignments/lambda-function-loader/README.md, misc/rules-and-grading.md
=> [hackathon2024]: Update information for hackathon.

.github/workflows/lab-archive.yml, gen-zip.py
On every push on the main branch, check if any files related to a lab
have changed. If so, create an archive with all files related to that
lab and push it to the `lab-archives` branch.
The `gen-zip.py` script will parse the `config.yaml` file, check the
last commit, and if the commit changes any file related to one of the
labs, extract all files related to that lab and create a zip archive.
=> Add workflow for uploading lab archives
