cs-pub-ro/operating-systems

- content/chapters/data/lab/content/working-memory.md
Rewrote part of a sentence to help ensure clarity and readability.
> data/lab: rewording and fix typo

- content/chapters/data/lab/content/working-memory.md
Changed the wrong value of the variable "a" in the explained comment from "7" to "42".
> Update working-memory.md from the data lab.

- content/chapters/data/lab/content/arena.md
Remove empty sections from the arena.
> content/data: Remove TODO exercises

- Makefile
The most important rules defined in this Makefile are:
- `make`: build the website locally in the `.output` directory
- `make serve`: to open a `python3` server which allows you to view the content at `http://localhost:8080/operating-systems`
- `make cleanall`: stop the server and remove the container and all docker images
> infra: Add Makefile to build the website

- content/assignments/lambda-function-loader/README.md
- content/assignments/lambda-function-loader/src/Makefile
- content/assignments/lambda-function-loader/src/ipc.c
- content/assignments/lambda-function-loader/src/ipc.h
- content/assignments/lambda-function-loader/src/server.c
- content/assignments/lambda-function-loader/src/server.h
- content/misc/rules-and-grading.md
- Add the hackathon description
- Add grading and submission instructions
- Update `config.yaml` to render the new changes
> content/assignments: Add "Lambda Function Loader" hackathon

- content/chapters/io/lab/solution/redirect/redirect.c
- content/chapters/io/lab/support/redirect/redirect.c
This pull request fixes the typo in both the solution and the support source files.
> io/lab: Fix "messge" typo in redirect.c

- config.yaml
- content/misc/rules-and-grading.md
Add the hackathon as another entry into `config.yaml`. Also add information about the hackathon rooms and the TAs involved.
> rules,config: Publish hackathon assignment

- content/chapters/io/lab/quiz/write-file-permissions.md
This pull request rewords the feedback of the quiz in order to clarify what the manual page means by "arbitrary bytes from the stack".
> io/lab: Clarify feedback for "write_file.txt Permissions" quiz

- content/assignments/lambda-function-loader/tests/ref/ref10
- content/assignments/lambda-function-loader/tests/ref/ref11
Add ref files for bonus tests: 10 & 11.
Add ref files for bonus tests: 10 & 11.
> content/assignments: Update "Lambda Function Loader" ref files

- CONTRIBUTING.md
For commits use the `<chapter>/<content_type>` prefix.
Although content is not yet updated / ported to the new structure, it's good to document the preferred commit prefix; and to start using it.
> CONTRIBUTING: Update commit details to the new structure

- content/misc/rules-and-grading.md
Rename the written part of the exam to 'Understanding Concepts'. State that students are allowed to use internet with the exception of collaborative resources.
> rules/exam: Rename second part of the exam

- .github/labeler.yml
- chapters/general/drills/tasks/digital-forensics.md
- config.yaml
- Add Markdown file storing the question scenario and questions
- Modify `config.yaml` to render the new task
- Update Labeler action to assign the `topic/general` label
> general/drills: Add "Digital Forensics" written task as exam

- chapters/general/drills/tasks/application-investigator.md
- config.yaml
Add Markdown file storing the question scenario and the questions Modify config.yaml to render the new task
- Modify config.yaml to render the new task
> general/drills: Add "Application Investigator" written task as exam

- chapters/general/drills/tasks/network-performance-utility.md
- config.yaml
edited config.yaml and network-performance-utility.md
- Modify `config.yaml` to render the new task
> general/drills: Add "Network Performance Utility" written task as exam

- chapters/general/drills/tasks/nightly-builds-system.md
- config.yaml
Add Markdown file storing the question scenario and the questions Modify config.yaml to render the new task
- Modify config.yaml to render the new task
> general/drills: Add "Nightly Builds System" written task as exam

- chapters/general/drills/tasks/blockchain-system.md
- chapters/general/drills/tasks/industrial-system.md
- chapters/general/drills/tasks/supervisor-type-service.md
- config.yaml
Add Markdown files storing the question scenario and the questions Modify config.yaml to render the new tasks
- Add Markdown files storing the question scenario and the questions
- Modify config.yaml to render the new tasks
> general/drills: Add the February 2023 written tasks as exams

- chapters/general/drills/tasks/backup-system.md
- chapters/general/drills/tasks/cloud-system.md
- chapters/general/drills/tasks/distributed-system.md
- chapters/general/drills/tasks/extending-an-app-manager.md
- chapters/general/drills/tasks/file-changes-notifier.md
- chapters/general/drills/tasks/header-analysis-application.md
- chapters/general/drills/tasks/intrusion-detection-system.md
- chapters/general/drills/tasks/library-warmer.md
- chapters/general/drills/tasks/memory-deduplication.md
- chapters/general/drills/tasks/resource-monitor.md
- chapters/general/drills/tasks/web-gui-1.md
- chapters/general/drills/tasks/web-gui-2.md
- config.yaml
- Add Markdown files storing the question scenario and the questions
- Modify `config.yaml` to render the new tasks
> general/drills: Add 2022 written tasks as exams

- content/assignments/minishell/tests/run_all.sh
Update `run_all.sh` to display `Total` points at the beginning of the line.
> content/assignments: Update minishell checker

- content/misc/rules-and-grading.md
Add written exam simulation info.
> rules/lecture-quiz: Add exam simulation info

- content/misc/rules-and-grading.md
Add additional requirements for the "Exam For Assignment Heroes" section.
> rules/exam: Update rules for exam exemption

- content/misc/resources.md
> Modify resources.md for 2024-2025 uni. year

- chapters/software-stack/applications/drills/tasks/app-investigation/README.md
- chapters/software-stack/high-level-languages/drills/tasks/high-level-lang/README.md
- chapters/software-stack/libc/drills/tasks/common-functions/README.md
- chapters/software-stack/libc/drills/tasks/libc/README.md
- chapters/software-stack/libraries/guides/static-dynamic/README.md
- chapters/software-stack/system-calls/drills/tasks/basic-syscall/README.md
- chapters/software-stack/system-calls/drills/tasks/libcall-syscall/README.md
- chapters/software-stack/system-calls/drills/tasks/syscall-wrapper/README.md
This makes it easier for students to navigate to the code folders without having to guess where to find each task.
> chapters/software-stack: Update the paths to all tasks to start fro `chapters/`

- chapters/software-stack/system-calls/drills/tasks/basic-syscall/Makefile
Move `support/src/tests/` to `support/tests/` so the `support/` folder matches the `solution/`.
> chapters/software-stack: Move generated tests at the same level as the source code

- config.yaml
- content/landing-page/README.md
- landing-page/README.md
It was a template page with no relevant information. Now it provides short descriptions for each chapter.
> config: Add content to the "Introduction" page

- chapters/software-stack/libc/drills/tasks/common-functions/solution/src/Makefile
- chapters/software-stack/libc/drills/tasks/common-functions/solution/src/main_printf.c
> Replace str* with os_str*

- chapters/software-stack/libc/drills/tasks/common-functions/solution/src/.gitignore
- chapters/software-stack/libc/drills/tasks/common-functions/solution/src/Makefile
- chapters/software-stack/libc/drills/tasks/common-functions/solution/src/main_printf.c
- chapters/software-stack/libc/drills/tasks/common-functions/solution/src/main_string.c
- chapters/software-stack/libc/drills/tasks/common-functions/solution/tests/test_strcat.c
- chapters/software-stack/libc/drills/tasks/libc/solution/main_printf.c
- chapters/software-stack/libc/drills/tasks/libc/support/main_printf.c
- chapters/software-stack/libc/reading/common-functions.md
- Add `main_string.c` and `string.*` to be used in the `reading/` activity.
- Fix `main_printf.c` to inlcude the system header `string.h` and not the local file.
> chapters/software-stack: Fix `common-functions` task.

- misc/rules-and-grading.md
- [ x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ x] Tested your changes against relevant architectures and platforms;
- [ x] Updated relevant documentation (if needed).
The current link to Software Stack chapter
https://cs-pub-ro.github.io/operating-systems/Lecture/Software%20Stack/ 
leads to a "Page not found" so I replaced it with
https://cs-pub-ro.github.io/operating-systems/Software%20Stack/Software-Stack
> misc/rules-and-grading.md: Fixed Software Stack chapter link

- chapters/software-stack/libc/reading/common-functions.md
- [ x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ x] Tested your changes against relevant architectures and platforms;
- [ x] Updated relevant documentation (if needed).
Modified `student@os:~/.../common-functions/support` path to
`student@os:~/.../common-functions/support/src` to show the 
correct location to run some commands.
> libc/reading: Fixed paths

- chapters/software-stack/libc/drills/tasks/common-functions/solution/src/main_printf.c
The solution now has the complete solution with comments both for `puthcar_()` and for using `sprintf()` + `write()` instead of `printf()`.
> chapters/software-stack: Add solution for `main_printf.c`

- content/assignments/async-web-server/tests/run_all.sh
Update score formatting for async-web-server `run_all.sh` to fix coding style issue.
> content/assignments: Update score formatting for async-web-server to fix coding style issue

- chapters/data/process-memory/drills/tasks/copy/generate_skels.py
- chapters/data/working-with-memory/drills/tasks/memory-access/generate_skels.py
- chapters/data/working-with-memory/drills/tasks/memory-corruption/generate_skels.py
- chapters/data/working-with-memory/drills/tasks/memory-corruption/solution/src/d_segfault.d
- chapters/data/working-with-memory/drills/tasks/memory-protection/generate_skels.py
- chapters/software-stack/applications/drills/tasks/app-investigation/generate_skels.py
- chapters/software-stack/high-level-languages/drills/tasks/high-level-lang/generate_skels.py
- chapters/software-stack/libc/drills/tasks/common-functions/generate_skels.py
- chapters/software-stack/libc/drills/tasks/libc/generate_skels.py
- chapters/software-stack/system-calls/drills/tasks/basic-syscall/generate_skels.py
- chapters/software-stack/system-calls/drills/tasks/syscall-wrapper/generate_skels.py
Set the variables `remove`, `replace_pairs`, and `end_string` for `.d` files so they are defined when calling the `process_file()` function.
Fixes: #109
> infra: Fix `generate_skels.py` for `.d` files

- .gitignore
- chapters/general/drills/tasks/syscall-tracing.md
- chapters/general/drills/tasks/sysinfo-library.md
- config.yaml
- Add "Syscall Tracer" and "Sysinfo Library" exams
- Modify `config.yaml` to render the above exams on the website
- Ignore the `.output/` directory containing the built website in the global `.gitignore`
> general/drills/tasks: Add exams for the 2024 special session

- chapters/data/process-memory/reading/process-memory.md
> chapters/data: Update task paths to start from chapters/

- chapters/data/working-with-memory/drills/tasks/memory-access/README.md
- chapters/data/working-with-memory/drills/tasks/memory-corruption/README.md
- chapters/data/working-with-memory/drills/tasks/memory-protection/README.md
Modified README.md paths from `/support/` to `/support/src/`.
> working-with-memory/drills: Modified some paths

- config.yaml
Move unattempted tasks from lab3 to lab4.
> data: Move tasks from lab3 to lab4

- config.yaml
Move the "Tasks" section at the start of each one-page lab so students aren't tempted to waste time reading the documentation during practical sessions when they should be going straight to the tasks.
> infra/config: Move tasks to the beginning of each lab

- chapters/data/process-memory/drills/tasks/copy/generate_skels.py
- chapters/data/working-with-memory/drills/tasks/memory-access/generate_skels.py
- chapters/data/working-with-memory/drills/tasks/memory-corruption/generate_skels.py
- chapters/data/working-with-memory/drills/tasks/memory-protection/generate_skels.py
- chapters/software-stack/applications/drills/tasks/app-investigation/generate_skels.py
- chapters/software-stack/high-level-languages/drills/tasks/high-level-lang/generate_skels.py
- chapters/software-stack/libc/drills/tasks/common-functions/generate_skels.py
- chapters/software-stack/libc/drills/tasks/libc/generate_skels.py
- chapters/software-stack/system-calls/drills/tasks/basic-syscall/generate_skels.py
- chapters/software-stack/system-calls/drills/tasks/syscall-wrapper/generate_skels.py
Modifies copies of `generate_skels.py` to support `.py` files.
> infra/`generate_skels.py`: Support Python-style comments

- chapters/compute/synchronization/slides/notifications.md
- chapters/compute/threads/slides/threads.md
PR #126 missed 2 links to images in the Compute chapter that are still broken. This commit fixes them.
> chapters/compute: Fix remaining broken links

- misc/resources.md
Changed the download link of the .qcow2 image to point to one built on x86_64 architecture.
> misc/resources.md: Update the instructions for UTM

- chapters/compute/copy-on-write/drills/tasks/page-faults/README.md
- chapters/compute/copy-on-write/drills/tasks/shared-memory/README.md
- chapters/compute/copy-on-write/guides/fork-faults/README.md
- chapters/compute/hardware-perspective/reading/hardware-perspective.md
- chapters/compute/processes-threads-apache2/drills/tasks/apache2/README.md
- chapters/compute/processes/drills/tasks/create-process/README.md
- chapters/compute/processes/drills/tasks/mini-shell/README.md
- chapters/compute/processes/drills/tasks/sleepy/README.md
- chapters/compute/processes/drills/tasks/wait-for-me-processes/README.md
- chapters/compute/processes/guides/create-process/README.md
- chapters/compute/processes/guides/sum-array-processes/README.md
- chapters/compute/scheduling/drills/tasks/libult/README.md
- chapters/compute/scheduling/guides/libult/README.md
- chapters/compute/synchronization/drills/tasks/race-condition/README.md
- chapters/compute/synchronization/drills/tasks/threadsafe-data-struct/README.md
- chapters/compute/synchronization/reading/synchronization.md
- chapters/compute/threads/drills/tasks/multithreaded/README.md
- chapters/compute/threads/drills/tasks/sum-array-bugs/README.md
- chapters/compute/threads/drills/tasks/sum-array/README.md
- chapters/compute/threads/guides/clone/README.md
- chapters/compute/threads/guides/sum-array-threads/README.md
- chapters/compute/threads/guides/wait-for-me-threads/README.md
- chapters/compute/threads/reading/threads.md
- chapters/compute/user-level-threads/guides/user-level-threads/README.md
- chapters/compute/user-level-threads/reading/user-level-threads.md
- config.yaml
Update text for the Compute chapter
labs by fixing typos,broken links,
task order etc.
> chapters/compute: Labs review

- config.yaml
- Move shared memory task to lab 8 because it requires knowledge of semaphores.
- Move Apache 2 simulator task to the end of lab 7 because interacting with docker might have confused students and delayed the following tasks.
> config: Rearrange tasks in labs 7 and 8

- chapters/compute/processes-threads-apache2/drills/tasks/apache2/README.md
Specify that students need to run `make run` to start the container and that `strace` needs to be run inside that container.
> chapters/compute: Clarify `apache2-simulator` task

- config.yaml
- Nest exams by year and season in `config.yaml`
- Mark 2022 exams as deprecated (their format is no longer used)
> exam: Add exam dates to `config.yaml`
